### ISSUE TITLE
[BUG] "undeclared function" errors with eXist 5.3.0-SNAPSHOT

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist-xqts-runner#11]
**Describe the bug**

While https://github.com/eXist-db/exist-xqts-runner/pull/10 allows me to compile and assemble the test runner, I'm getting "undeclared function" errors when calling function-specific tests such as `fn-format-number` and `fn-analyze-string`.

**Expected behavior**

I expected the test suite to produce at least some passed tests. Instead, all non-skipped tests fail.

**To Reproduce**

```bash
sbt assembly
cd target/scala-2.13
exist-xqts-runner-assembly-1.0.0.jar -ts fn-analyze-string
```

Then open the junit results, and you'll see the screenshot below. (In contrast, see the screenshot at https://github.com/eXist-db/exist/pull/3130.)

**Unit Test**

n/a

**Screenshots**

> <img width="1252" alt="Screen Shot 2020-10-19 at 12 57 39 PM" src="https://user-images.githubusercontent.com/59118/96485947-b3c5f500-120a-11eb-8aea-fb8cb2b6c6e4.png">

**Context (please always complete the following information):**
 - OS: [e.g. macOS 10.14.6]: macOS 10.15.7
 - eXist-db Version: [e.g. 5.1.1]: eXist 5.3.0-SNAPSHOT 67295356d46815997774626406b978931e9db2bf 20200915171140 (a build of https://github.com/eXist-db/exist/pull/3530)
 - Java Version: [e.g. Java8u121]: Liberica openjdk version "11.0.8" 2020-07-14 LTS
-  App Version: [e.g. 1.0.0]: 1.0.0 with https://github.com/eXist-db/exist-xqts-runner/pull/10

**Additional context**
- How is eXist-db installed? [e.g. JAR installer, DMG, … ] built from source
- Any custom changes in e.g. `conf.xml`? none

**Comment by adamretter** [comment]
@joewiz I believe this is fixed in the `5.3.0-SNAPSHOT` branch. 

I was able to run the following:

```
sbt clean compile
sbt assembly
target/scala-2.13/exist-xqts-runner-assembly-1.0.0.jar -ts fn-analyze-string
```

Which produced the following:

![Uploading Screenshot 2020-10-19 at 19.49.46.png…]()

**Comment by adamretter** [comment]
Please reopen if I have misunderstood...

**Comment by joewiz** [comment]
@adamretter Thank you! Unfortunately my results have not changed, after pulling in the latest 5.3.0-SNAPSHOT branch of this repo. This must be user error on my part, and I am guessing that it stems from how I built eXist from your PR (mentioned at https://github.com/eXist-db/exist/pull/3530#issuecomment-711115414). I checked out your PR branch and built/installed it with `mvn clean package install -DskipTests=true`. Then I ran your `sbt` commands as above on the same system. Does this sound like the correct build/installation procedure, to ensure that sbt picks up the correct build of eXist?

**Comment by adamretter** [comment]
I suspect that eXist-db/exist#3530 is not up to date with the head of 5.3.0-SNAPSHOT as it was opened a while ago. I have now rebased that PR onto HEAD, can you try again?

**Comment by joewiz** [comment]
@adamretter Thank you! I performed a fresh checkout of your https://github.com/eXist-db/exist/pull/3530, and repeated the eXist clean/install + exist-xqts-runner clean/compile/assembly, but the resulting junit HTML still shows 28 failures. To confirm my branches & revisions:

```
joe@choskimac-iii exist-xqts-runner % git branch
* exist-5.3.0-SNAPSHOT
  master
joe@choskimac-iii exist-xqts-runner % git rev-parse HEAD                                                          
af68cc701e54656c04d565e02afda05d7d25b193

joe@choskimac-iii exist % git branch                                                                                                                                                                                                                     
  develop
* pullrequests/3530-adamretter/refactor/regex-functions
joe@choskimac-iii exist % git rev-parse HEAD                                                                                                                                                                                                             
88fb09d9e22071d4b2484811f85ec993a7331814
```

Attached is my console output: [exist-xqts-runner-build-run-log-2.txt](https://github.com/eXist-db/exist-xqts-runner/files/5416787/exist-xqts-runner-build-run-log-2.txt)

A quick diff of the 2 console logs shows basically no difference, except whereas the old version said this on line ~408:

```
21 Oct 2020 00:52:29,983 [XQTSRunnerSystem-akka.actor.default-dispatcher-10] WARN  (XQueryContext.java [instantiateModule]:1633) - error while instantiating module class org.exist.xquery.functions.fn.FnModule 
java.lang.NoClassDefFoundError: Could not initialize class org.exist.xquery.functions.fn.FnModule
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
```

The new version says this:

```
21 Oct 2020 10:46:58,399 [XQTSRunnerSystem-akka.actor.default-dispatcher-19] WARN  (XQueryContext.java [instantiateModule]:1633) - error while instantiating module class org.exist.xquery.functions.fn.FnModule 
java.lang.ExceptionInInitializerError: null
	at org.exist.xquery.functions.fn.FnModule.<clinit>(FnModule.java:213) ~[exist-xqts-runner-assembly-1.0.0.jar:1.0.0]
```

Does this shed any light on the issue, by chance?

**Comment by adamretter** [comment]
@joewiz I can't reproduce what you are seeing...

1. I have just run `mvn install` on the HEAD of eXist-db to get the latest 5.3.0-SNAPSHOT installed.
2. I also just merged all changes for exist-xqts-runner to master to make things simpler. I then did a pull and `sbt clean assembly` there and I get these results:

```
❯ target/scala-2.13/exist-xqts-runner-assembly-1.0.0.jar -ts fn-analyze-string

22 Oct 2020 15:12:37,178 [main] INFO  (slf4j.scala [info]:159) - eXist-db XQTS Runner starting for: XQTS_3_1
22 Oct 2020 15:12:37,511 [main] INFO  (slf4j.scala [info]:159) - Found XQTS at: work/QT3_1_0
22 Oct 2020 15:12:37,515 [main] INFO  (slf4j.scala [info]:159) - Starting an embedded instance of eXist-db...
22 Oct 2020 15:12:37,527 [main] WARN  (ConfigurationHelper.java [getExistHome]:133) - conf.xml file was found on the classpath, but inside a Jar file! Derived EXIST_HOME from Jar's parent folder: /Users/aretter/code/exist-xqts-runner/target/scala-2.13
22 Oct 2020 15:12:37,559 [main] WARN  (ConfigurationHelper.java [getExistHome]:133) - conf.xml file was found on the classpath, but inside a Jar file! Derived EXIST_HOME from Jar's parent folder: /Users/aretter/code/exist-xqts-runner/target/scala-2.13
22 Oct 2020 15:12:37,562 [main] WARN  (ConfigurationHelper.java [getExistHome]:133) - conf.xml file was found on the classpath, but inside a Jar file! Derived EXIST_HOME from Jar's parent folder: /Users/aretter/code/exist-xqts-runner/target/scala-2.13
22 Oct 2020 15:12:37,659 [main] WARN  (ConfigurationHelper.java [getExistHome]:133) - conf.xml file was found on the classpath, but inside a Jar file! Derived EXIST_HOME from Jar's parent folder: /Users/aretter/code/exist-xqts-runner/target/scala-2.13
22 Oct 2020 15:12:37,660 [main] WARN  (QuartzSchedulerImpl.java [getQuartzProperties]:149) - Could not load Quartz Scheduler properties, will use defaults.
22 Oct 2020 15:12:38,261 [main] INFO  (slf4j.scala [info]:159) - eXist-db 5.3.0-SNAPSHOT (97e8044) OK.
22 Oct 2020 15:12:38,318 [XQTSRunnerSystem-akka.actor.default-dispatcher-6] INFO  (slf4j.scala [info]:159) - Running XQTS: XQTS_3_1
22 Oct 2020 15:12:38,347 [XQTSRunnerSystem-akka.actor.default-dispatcher-5] INFO  (slf4j.scala [info]:159) - Parsing XQTS Catalog: work/QT3_1_0/catalog.xml...
22 Oct 2020 15:12:38,517 [XQTSRunnerSystem-akka.actor.default-dispatcher-6] INFO  (slf4j.scala [info]:159) - Parsing XQTS TestSet: work/QT3_1_0/fn/analyze-string.xml...
22 Oct 2020 15:12:38,527 [XQTSRunnerSystem-akka.actor.default-dispatcher-5] INFO  (slf4j.scala [info]:159) - Parsed XQTS Catalog OK.
22 Oct 2020 15:12:38,574 [XQTSRunnerSystem-akka.actor.default-dispatcher-6] INFO  (slf4j.scala [info]:159) - Parsed XQTS TestSet: work/QT3_1_0/fn/analyze-string.xml OK.
22 Oct 2020 15:12:38,817 [XQTSRunnerSystem-akka.actor.default-dispatcher-10] INFO  (slf4j.scala [info]:159) - Serializing results for TestSet: fn-analyze-string (work/QT3_1_0/fn/analyze-string.xml)...
22 Oct 2020 15:12:38,851 [XQTSRunnerSystem-akka.actor.default-dispatcher-10] INFO  (slf4j.scala [info]:159) - Serialized results for TestSet: fn-analyze-string OK.
22 Oct 2020 15:12:38,852 [XQTSRunnerSystem-akka.actor.default-dispatcher-8] INFO  (slf4j.scala [info]:159) - Aggregating results report...
22 Oct 2020 15:12:39,568 [XQTSRunnerSystem-akka.actor.default-dispatcher-8] INFO  (slf4j.scala [info]:159) - Aggregated results report OK (716 ms).
22 Oct 2020 15:12:39,569 [XQTSRunnerSystem-akka.actor.default-dispatcher-8] INFO  (slf4j.scala [info]:159) - Completed XQTS in (1252 ms)
```

p.s. I am using OpenJDK 8 - what JDK are you using? Does that make a difference?

**Comment by joewiz** [comment]
@adamretter Your suggestion to switch from JDK 11 to JDK 8 seems to have done the trick. Specifically, I switched from Liberica OpenJDK version "11.0.8" 2020-07-14 LTS to Liberica OpenJDK version "1.8.0_265" (via homebrew tap bell-sw/liberica, I switched from `liberica-jdk11-full` to `liberica-jdk8-full`). Doing this, I finally get passing results! Thank you, Adam!

**Comment by dizzzz** [comment]
you can NOT compile with java11 and run with java8..

**Comment by joewiz** [comment]
I didn’t mix versions, to my knowledge. I compiled and ran both eXist and the exist-cats-runner under Java 11 - and got the errors reported above. Only when compiling/running with Java 8 was I able to get the expected results.

Was I wrong to try using Java 11 in the first place?

**Comment by adamretter** [comment]
@joewiz We are using Scala 2.13.3, so it should be fine with Java 11: https://docs.scala-lang.org/overviews/jdk-compatibility/overview.html

CI also shows that we can build on JDK 8 - 13: https://travis-ci.com/github/eXist-db/exist-xqts-runner

As it sounds like a runtime issue, I would have to investigate further. How pressing is this?

**Comment by joewiz** [comment]
@adamretter Not pressing at all. Now that I know how to run it, I can make full use of the utility.
